### ISSUE TITLE
Misplaced noalgin

### ISSUE THREAD

**Issue by nsauter** [cab-1729/Pandoc-Themes#3]
Hi!

With every template i use i get a Error when executing _pandoc --pdf-engine=xelatex -f markdown -t pdf --template=notes-dark.tex test.md -o test.pdf_

Error producing PDF.
! Misplaced \noalign.
\newpage ->\noalign 
                    {\break }
l.367 \end{document}

How can i fix this?

**Comment by cab-1729** [comment]
Since this issue is closed I am assuming the problem is resolved. If not, please respond.
