### ISSUE TITLE
pandoc-fonts messes up system fonts used for other applications

### ISSUE THREAD

**Issue by kitesi** [cab-1729/Pandoc-Themes#4]
Hi! Great project. The only issue I having is that when I copy pandoc-fonts into my `/usr/share/fonts`, it messes up my fonts for other applications like firefox. I can revert this by deleting the folder, but how would i be able to keep the fonts, and have it isolated from use for other apps? I have looked online to no avail.

**Comment by cab-1729** [comment]
Fonts on webpages do tend to change when new fonts are installed on the system. This has nothing to with the fonts or the location, it's just the way websites are structured. They look for a font on your system and display it.

You can read about this exact behavior [here](https://www.reddit.com/r/firefox/comments/16qj7wz/website_font_changed_after_install_of_new_font/).

To remedy this you need to personally change your browser or search engine settings, perhaps by adding custom css via an extension.

Fonts on GNU/Linux are always kept in ```/usr/share/fonts``` by convention. Placing fonts over there make them accessible to all applications. You will encounter similar behavior if you install *any* font on your system. Your problem isn't specific to this project.
